---
- name: Get list of hosts for the root user
  command: "{{ mariadb_mysql_binary }} -NBe
    \"SELECT Host
    FROM mysql.user
    WHERE User = 'root'
    ORDER BY (Host='localhost') ASC\""
  register: mariadb_root_hosts
  changed_when: False
  check_mode: False

- name: Disallow root login remotely
  mysql_user:
    name: "root"
    host: "{{ item }}"
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: item not in ['localhost', '127.0.0.1', '::1']
  loop: "{{ mariadb_root_hosts.stdout_lines | default([]) }}"

- name: Update MariaDB root password
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  register: __mariadb_rootpw_update
  when: item in ['localhost', '127.0.0.1', '::1']
  loop: "{{ mariadb_root_hosts.stdout_lines | default([]) }}"

- name: Copy .my.cnf file with root password credentials
  template:
    src: "root-my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: __mariadb_rootpw_update.changed

- name: Get list of hosts for the anonymous user
  command: "{{ mariadb_mysql_binary }} -NBe \"SELECT Host FROM mysql.user WHERE User = ''\""
  register: mariadb_anonymous_hosts
  changed_when: False
  check_mode: False

- name: Remove anonymous MariaDB users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ mariadb_anonymous_hosts.stdout_lines | default([]) }}"

- name: Remove MariaDB test database
  mysql_db:
    name: "test"
    state: "absent"
    login_unix_socket: /var/run/mysqld/mysqld.sock

...
